print "*********"
print "    *"
print " *  *  *"
print " *  *  *"
print " *  *  *"
print " ******* ***      Thomas"
print " *  *  **   *          H."
print " *  *  *          Cormen"
print " *  *  *"
print "       *"
print "        *   *"
print "         ***"
