from cs1lib import *
from cell import *

def main():
    c1 = Cell(0, 0)
    c1.draw()
    request_redraw()
    print "c1 is living = ", c1.is_living()
    sleep(1)
    c1.flip()
    c1.draw()
    request_redraw()
    print "c1 is living = ", c1.is_living()
    sleep(1)
    c1.flip()
    c1.draw()
    request_redraw()
    print "c1 is living = ", c1.is_living()
    sleep(1)
    c2 = Cell(1, 1)
    c2.draw()
    request_redraw()
    print "c2 is living = ", c2.is_living()
    sleep(1)
    c2.revive()
    c2.draw()
    request_redraw()
    print "c2 is living = ", c2.is_living()
    sleep(1)
    c2.kill()
    c2.draw()
    request_redraw()
    print "c2 is living = ", c2.is_living()
    sleep(1)

start_graphics(main)